import React from 'react'

const index = () => {
    return (
        <div style={{
            position: 'relative',
        }}>
            <img style={{
                position: 'sticky',
                top: '0',
            }} src="https://via.placeholder.com/150" alt="sticky image" />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porttitor lorem ac magna dapibus tincidunt. Sed euismod urna sapien, a lacinia nunc mattis eu. Suspendisse potenti. Donec convallis aliquet quam, at commodo mi sodales nec. Vivamus eu aliquet orci. Pellentesque euismod ultrices nisl, sit amet ullamcorper leo gravida quis. Sed auctor nisi non eros feugiat, sit amet tincidunt mauris bibendum. Pellentesque ac massa eget risus luctus aliquet. Mauris ultrices, quam a blandit imperdiet, nulla enim blandit lorem, eget sagittis sapien diam at quam. Nulla et nunc odio. Donec tristique orci quam, in malesuada dolor facilisis sed.</p>
            <p>Integer et odio euismod, tincidunt enim vel, cursus velit. Nam semper orci a nibh semper, sed pharetra nulla interdum. Fusce condimentum dolor vel erat gravida, a luctus quam pharetra. Nunc id purus euismod, volutpat turpis eu, bibendum quam. Integer in nulla eget massa lacinia sodales eget vitae nibh. Curabitur tempor tortor ipsum, ac sagittis massa posuere ut. Ut a elit ante. Aenean ac augue vitae est auctor pulvinar. Nullam euismod ligula non ultricies imperdiet. Integer sit amet arcu eu nisi feugiat mattis. Maecenas luctus urna ac eros ornare fringilla. Maecenas placerat tellus enim, sed blandit lectus iaculis eu. Nulla facilisi.</p>
        </div>
    );
}

export default index